Fix graph access to handle missing class_type key
Following error occurs when request distirbuted areas. This change resoves the error.

File "/usr/local/lib/python3.10/site-packages/cimgraph/databases/__init__.py", line 285, in create_object
    if identifier in graph[class_type]:
KeyError: <class 'cimgraph.data_profile.cimhub_2023.cimhub_2023.PowerTransformer'>